apiVersion: apps/v1
kind: Deployment
metadata:
  name: remcord-exchange-server
  labels:
    app: remcord-exchange-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: remcord-exchange-server
  template:
    metadata:
      labels:
        app: remcord-exchange-server
    spec:
      containers:
      - name: remcord-exchange-server
        image: remcord-exchange-server:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
      imagePullSecrets:
      - name: myregistrykey
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: remcord-exchange-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: remcord-exchange-server
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80
