apiVersion: v1
kind: Service
metadata:
  name: remcord-exchange-server-service
  labels:
    app: remcord-exchange-server
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: remcord-exchange-server
